import pandas as pd

df = pd.read_csv('C:\\Users\\user\\Downloads\\Detailed_Post_Performance.csv')

code = '''
output_df = df.sort_values('Reach', ascending=False).head(1)
fig = plt.figure()
plt.plot(df['Time Posted'], df['Reach'])
plt.title('Reach of Social Media Posts')
plt.xlabel('Time Posted')
plt.ylabel('Reach')
plt.xticks(rotation=45)
plt.show()
'''
exec(code)
